// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtmpgveogtzvybgcmxug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0bXBndmVvZ3R6dnliZ2NteHVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4Nzk4NDUsImV4cCI6MjA3MzQ1NTg0NX0.G-ezl9AgRKUXBPItcm-3k-nzxV2Pue8_wFClKgxg5lQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});